spring.application.name=OAUTH2SocialLogin

server.port=8081

# H2 database settings
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Let Spring Boot use your schema.sql & data.sql
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.datasource.initialization-mode=always

# H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true

management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [%green(${spring.application.name:}),%blue(%X{traceId:-}),%red(%X{spanId:-})]
#logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
logging.level.root = info
logging.level.org.springframework.security=DEBUG


management.endpoints.web.exposure.include=*
management.metrics.distribution.percentiles-histogram.greeting=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true


management.endpoint.health.show-details=always


#spring.security.user.name=easybank
#spring.security.user.password=123456

#config code is not required if we use in properties file
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23liJs4HyS50OjQbRx}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:af8ef9e723e59b895f99d2452abcac3f9259c058}

spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID:741652962004867}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET:6ae6c49e1aed9d46d0fe25241feb2d3b}